### ISSUE TITLE
Progress ring locking

### ISSUE THREAD

**Issue by CAPCHIK** [RTUITLab/StuDo-iOS#4]
The progress ring is locked after folding.

![ezgif com-optimize](https://user-images.githubusercontent.com/12235437/80137501-0dc36600-85ac-11ea-9fec-9143cc26d5ed.gif)

**Comment by qstrnd** [comment]
Этот баг появился после отключения сети или в результате другого действия? Что имеется в виду под «Folding”?

**Comment by CAPCHIK** [comment]
Шаги для воспроизведения:

1. Потянуть за шторку
2. Не дождавшись завершения загрузки свернуть приложение, выйти на главное меню
3. Вернуться в приложение

Итог - кольцо загрузки будет заблокировано в одном состоянии

**Comment by qstrnd** [comment]
Fixed in b9ffdeb63cfbe310ebad3c3f529099a0a723ef2b
