### ISSUE TITLE
“No ads” message does not disappear

### ISSUE THREAD

**Issue by CAPCHIK** [RTUITLab/StuDo-iOS#6]
После создания первого события сообщение об отсутствии событий в соседней

Шаги для повторения:

1. Удалить все свои объявления, очистить закладки
2. На главном экране создать объявление
3. Переключиться на экран со своими объявлениями - там будет отображаться созданное объявление, но сообщение об отсутствии останется на месте
4. Добавить созданное объявление в избранное
5. Переключиться на экран с избранными объявлениями, избранное отобразится, но сообщение не пропадет.

После обновления экранов старое сообщение пропадает.

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/12235437/80138886-38aeb980-85ae-11ea-8c16-a9d2071e3dda.gif)

**Comment by qstrnd** [comment]
Fixed in fc1c8b553dfc008c724f391a66b6434c319f6b76
