### ISSUE TITLE
Cannot fill ID

### ISSUE THREAD

**Issue by CAPCHIK** [RTUITLab/StuDo-iOS#8]
При попытке заполнить идентификатор студента открывается числовая клавиатура, из-за этого нельзя заполнить букву в номере студенческого билета.

![image](https://user-images.githubusercontent.com/12235437/80140848-3ef26500-85b1-11ea-85f9-cd515b8d541c.png)

**Comment by qstrnd** [comment]
Fixed in fc1c8b553dfc008c724f391a66b6434c319f6b76
